# Generated by Django 5.1.7 on 2025-06-18 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('audio', 'Audio'), ('video', 'Vidéo')], max_length=10)),
                ('emetteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appels_emis', to=settings.AUTH_USER_MODEL)),
                ('recepteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appels_recus', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(choices=[('privee', 'Privée'), ('groupe', 'Groupe')], default='privee', max_length=10)),
                ('confidentialite', models.CharField(choices=[('public', 'Public'), ('prive', 'Privé'), ('secret', 'Secret')], default='public', max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='discussions/photos/')),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('archivee', 'Archivée')], default='active', max_length=20)),
                ('createur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussions_creees', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='discussions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_modification'],
            },
        ),
        migrations.CreateModel(
            name='ActionDiscussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('creation', 'Création'), ('ajout_participant', 'Ajout participant'), ('suppression_participant', 'Suppression participant'), ('changement_nom', 'Changement de nom'), ('changement_photo', 'Changement de photo')], max_length=30)),
                ('details', models.JSONField(blank=True, null=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='discussions.discussion')),
            ],
            options={
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('text', 'Texte'), ('media', 'Média'), ('system', 'Système')], default='text', max_length=10)),
                ('media', models.FileField(blank=True, null=True, upload_to='messages/media/')),
                ('media_type', models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Vidéo'), ('audio', 'Audio'), ('document', 'Document')], max_length=10, null=True)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('lu', models.BooleanField(default=False)),
                ('supprime', models.BooleanField(default=False)),
                ('destinataire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to=settings.AUTH_USER_MODEL)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='discussions.discussion')),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL)),
                ('message_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='discussions.message')),
            ],
            options={
                'ordering': ['date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='ParametresDiscussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications', models.BooleanField(default=True)),
                ('epingle', models.BooleanField(default=False)),
                ('archive', models.BooleanField(default=False)),
                ('couleur', models.CharField(blank=True, max_length=7, null=True)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussions.discussion')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('utilisateur', 'discussion')},
            },
        ),
        migrations.CreateModel(
            name='StatutLectureMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lu', models.BooleanField(default=False)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuts_lecture', to='discussions.message')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('message', 'utilisateur')},
            },
        ),
    ]
